name: Java Build and Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21' # Specify the JDK version
          distribution: 'adopt' # Specify the distribution, for example, 'adopt'

      - name: Set API_KEY environment variable
        run: echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV

      - name: Compile Java code
        run: mvn compile

      - name: Run Java application
        run: mvn exec:java
